repos:
   - repo: https://github.com/pre-commit/pre-commit-hooks
     rev: v4.4.0
     hooks:
         - id: check-case-conflict
         - id: check-merge-conflict
         - id: trailing-whitespace
         - id: check-ast
         - id: check-added-large-files
         - id: check-toml
         - id: check-json
         - id: check-yaml


   - repo: https://github.com/psf/black
     rev: 23.1.0
     hooks:
         - id: black
         - id: black-jupyter


   - repo: https://github.com/pre-commit/mirrors-mypy
     rev: v1.0.1
     hooks:
         - id: mypy
           args: []
           additional_dependencies: ["types-PyYAML", "types-aiofiles", "types-setuptools"]
           exclude: (/test_|tests/|alembic/)


   - repo: https://github.com/asottile/pyupgrade
     rev: v3.3.1
     hooks:
         - id: pyupgrade
           args: [--py38-plus]


   - repo: https://github.com/timothycrosley/isort
     rev: 5.12.0
     hooks:
         - id: isort
           args: ["--profile", "black"]
           exclude: (/test_|tests/|alembic/)


   - repo: https://github.com/PyCQA/flake8
     rev: 6.0.0
     hooks:
         - id: flake8
           name: flake8
           entry: flake8
           language: python
           types: [python]
           args: [--config, .flake8]
           exclude: (/test_|tests/|alembic/)


   - repo: https://github.com/pycqa/pylint
     rev: v2.16.1
     hooks:
         - id: pylint
           exclude: (/test_|tests/|alembic/)


   - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
     rev: v1.0.6
     hooks:
         - id: python-bandit-vulnerability-check
           args: [--recursive, clumper]